### ISSUE TITLE
QNODE head and tail pointers not accessible outside of charQueue.c

### ISSUE THREAD

**Issue by glaslan** [glaslan/cscn71030-sec1-group5#12]
Description: The head and tail pointers for the QNODE can not be accessed in the main.c file.

Version: [ccee968](https://github.com/glaslan/cscn71030-sec1-group5/commit/ccee9689d7fd50669096c5d8586195da8bbb0522)

Additional context: The parser's parseProgram(QNODE*) requires the head of the queue as a parameter. This function is invoked in main.c.

Possible Solution: Either create a Queue structure that holds the head and the tail pointers (best practice) or make the static pointers globally accessible (gets the job done).

**Comment by destinyloua** [comment]
made struct for queue head and tail
