### ISSUE TITLE
Whitespace recognized as an invalid token

### ISSUE THREAD

**Issue by glaslan** [glaslan/cscn71030-sec1-group5#16]
Description: Whitespace such as spaces, tabs, and newlines are recognized as an INVALID token instead of being ignored.

Version: [2817b80](https://github.com/glaslan/cscn71030-sec1-group5/commit/2817b80b6ed46f45bf70aea95efb1435d136bfac)

Possible Solution: Cases for whitespace characters must be added to the lexer switch so that they are passed over.

**Comment by destinyloua** [comment]
added whitespace cases to be ignored
